CREATE TABLE hotels (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name varchar(20) NULL,
	category int NULL,
	CONSTRAINT hotel_pkey PRIMARY KEY (id)
);

CREATE TABLE public.bookings (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"date_from" date NOT null,
	"date_to" date NOT null,
	id_hotel int4 NOT null,
	email varchar NOT NULL,
	CONSTRAINT bookings_pkey PRIMARY KEY (id),
	CONSTRAINT hotel_fk FOREIGN KEY (id_hotel) REFERENCES public.hotels(id)
	
);

CREATE TABLE public.availabilities (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"date" date NOT NULL,
	id_hotel int4 NOT NULL,
	rooms int4 NOT NULL,
	CONSTRAINT availabilities_pkey PRIMARY KEY (id),
	CONSTRAINT hotel_fk FOREIGN KEY (id_hotel) REFERENCES public.hotels(id)
);